on:
  workflow_call:
    inputs:
      firebase_env:
        type: string
        required: true
    secrets:
      git_crypt_key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unlock git crypt
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.git_crypt_key }}
      - uses: ./.github/actions/pnpm-install
      - run: pnpm run build:firebase:${{ inputs.firebase_env }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'build'
          path: dist/nuxt/
