on:
  workflow_call:
    secrets:
      firebaseToken:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - run: pnpm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.firebaseToken }}
