on:
  workflow_call:
    inputs:
      projectId:
        required: false
        type: string
        default: fir-89cb3
    secrets:
      firebaseServiceAccount:
        required: true
      repoToken:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - uses: actions/download-artifact@v4
        with:
          name: 'build'
          path: dist/nuxt
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.repoToken }}
          firebaseServiceAccount: ${{ secrets.firebaseServiceAccount }}
          projectId: ${{ inputs.projectId }}
