name: 'Deploy to staging'

on:
  pull_request:

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://headwood-1cdfb.web.app
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NUXT_FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'
          envkey_NUXT_FIREBASE_APP_ID: '${{ env.FIREBASE_APP_ID }}'
          envkey_NUXT_FIREBASE_AUTH_DOMAIN: '${{ env.FIREBASE_AUTH_DOMAIN }}'
          envkey_NUXT_FIREBASE_MEASUREMENT_ID: '${{ env.FIREBASE_MEASUREMENT_ID }}'
          envkey_NUXT_FIREBASE_MESSAGING_SENDER_ID: '${{ env.FIREBASE_MESSAGING_SENDER_ID }}'
          envkey_NUXT_FIREBASE_PROJECT_ID: '${{ env.FIREBASE_PROJECT_ID }}'
          envkey_NUXT_FIREBASE_STORAGE_BUCKET: '${{ env.FIREBASE_STORAGE_BUCKET }}'
          file_name: .env.staging
          fail_on_empty: false
      - run: pnpm run build:firebase:staging
      - run: ls -al dist/nuxt/server
      - run: cat dist/nuxt/server/.env.staging
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      - run: pnpm exec firebase deploy --only auth,firestore,functions,hosting
