name: 'Deploy to staging'

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unlock git crypt
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: ./.github/actions/pnpm-install
      - run: pnpm run check
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - uses: actions/checkout@v4
      - name: Unlock git crypt
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: ./.github/actions/pnpm-install
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.STAGING_FIREBASE_SERVICE_ACCOUNT }}'
      - run: pnpm run deploy:staging
