name: 'Deploy for preview'

on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    name: Build for preview
    uses: ./.github/workflows/build.yml
  check:
    name: Check for preview
    uses: ./.github/workflows/check.yml
  preview:
    name: Deploy for preview
    uses: ./.github/workflows/deploy.yml
    needs:
      - build
      - check
    with:
      channelId: live
    secrets:
      repoToken: ${{ secrets.GITHUB_TOKEN }}
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_89CB3 }}
