on:
  pull_request:
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build:
    uses: ./.github/workflows/build.yml
  check:
    uses: ./.github/workflows/check.yml
  preview:
    uses: ./.github/workflows/deploy.yml
    needs:
      - build
      - check
    secrets:
      repoToken: ${{ secrets.GITHUB_TOKEN }}
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_89CB3 }}
