name: 'Deploy to staging'

on:
  pull_request:

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
  build:
    name: Build for staging
    uses: ./.github/workflows/build.yml
    with:
      firebase_env: staging
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
  test-e2e:
    name: Test e2e for staging
    needs:
      - build
    uses: ./.github/workflows/test-e2e.yml
    with:
      firebase_env: staging
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
  test-unit:
    name: Test unit
    uses: ./.github/workflows/test-unit.yml
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
  deploy:
    name: Deploy to staging
    needs:
      - check
      - build
      - test-unit
      - test-e2e
    uses: ./.github/workflows/deploy.yml
    with:
      firebase_env: staging
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
      firebase_service_account: '${{ secrets.STAGING_FIREBASE_SERVICE_ACCOUNT }}'
  test-e2e-live:
    name: Test e2e for live staging
    needs:
      - deploy
    uses: ./.github/workflows/test-e2e.yml
    with:
      firebase_env: staging
      base_url: https://headwood-1cdfb.web.app/
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
