name: 'Deploy to staging'

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  check:
    name: Check
    uses: ./.github/workflows/check.yml
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://headwood-1cdfb.web.app
    needs:
      - build
      - check
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - name: '📦 Download artifacts'
        uses: actions/download-artifact@v4
        with:
          name: 'build'
          path: dist/nuxt/
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      - run: pnpm exec firebase -P "${NUXT_FIREBASE_PROJECT_ID}" deploy --only auth,firestore,functions,hosting
        env:
          NUXT_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          NUXT_FIREBASE_APP_ID: ${{ env.FIREBASE_APP_ID }}
          NUXT_FIREBASE_AUTH_DOMAIN: ${{ env.FIREBASE_AUTH_DOMAIN }}
          NUXT_FIREBASE_MEASUREMENT_ID: ${{ env.FIREBASE_MEASUREMENT_ID }}
          NUXT_FIREBASE_MESSAGING_SENDER_ID: ${{ env.FIREBASE_MESSAGING_SENDER_ID }}
          NUXT_FIREBASE_PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID }}
          NUXT_FIREBASE_STORAGE_BUCKET: ${{ env.FIREBASE_STORAGE_BUCKET }}
